// Copyright 2017 Sardak Software

#ifndef REALMSERVEREMULATOR_PROTOCOL_PACKET_TYPE_H_
#define REALMSERVEREMULATOR_PROTOCOL_PACKET_TYPE_H_

namespace protocol
{

    enum class PacketType
    {
        kConnect = 0x01,
        kEncryption = 0x04,
        kRequestPatch = 0x06,
        kGetPatchBlock = 0x07,
        kGetPatchInfo = 0x08,
        kCheckLogin = 0x0e,
        kErrorLog = 0x0f,
        kLogin = 0x10,
        kPing = 0x11,
        kQueryCharacters = 0x12,
        kLoginAccount = 0x15,
        kDisconnect = 0x16,
        kPage = 0x17,
        kNotify = 0x18,
        kAck = 0x19,
        kNak = 0x1a,
        kNewRoom = 0x20,
        kRoomData = 0x21,
        kTalk = 0x25,
        kChat = 0x26,
        kAction = 0x29,
        kMovieList = 0x2a,
        kDestroy = 0x2d,
        kCreateCharacter = 0x30,
        kDestroyCharacter = 0x31,
        kShiftRoom = 0x34,
        kGetBiography = 0x37,
        kUpdateBiography = 0x38,
        kGetDescription = 0x39,
        kGetExtendedProps = 0x3a,
        kSetHeadData = 0x3b,
        kPlayerList = 0x3d,
        kCombatMove = 0x44,
        kCombatExit = 0x45,
        kCombatFlee = 0x46,
        kGetShopInfo = 0x47,
        kBuyBulk = 0x48,
        kExamineItem = 0x49,
        kSellItem = 0x4a,
        kGetPrice = 0x4b,
        kMoneyDrop = 0x4c,
        kMoneyPut = 0x4d,
        kMoneyGive = 0x4e,
        kMoneyTake = 0x4f,
        kCastSpell = 0x50,
        kGetBookInfo = 0x52,
        kGetBookPage = 0x53,
        kSendFatal = 0x54,
        kJoinGroup = 0x57,
        kLeaveGroup = 0x58,
        kGroupKick = 0x59,
        kGroupInvite = 0x5a,
        kGetStartingPosn = 0x5c,
        kChangePassword = 0x5d,
        kQueryHouse = 0x5e,
        kGetEntryInfo = 0x5f,
        kLoginQueue = 0x62,
        kGetRouteList = 0x64,
        kRecharge = 0x65,
        kGetRechargePrice = 0x66,
        kSetTitle = 0x67,
        kGetTopic = 0x69,
        kGetTopicText = 0x6a,
        kLastTopic = 0x6b,
        kAcceptQuest = 0x6c,
        kDeclineQuest = 0x6d,
        kGetQuestList = 0x6e,
        kMixObject = 0x6f,
        kCombatAction = 0x70,
        kWhatsNew = 0x72,
        kSetEngraveText = 0x73,
        kGetLookInfo = 0x74,
        kSellCrystals = 0x75,
        kRepair = 0x7a,
        kGetRepairPrice = 0x7b,
        kUpdateCharacter = 0x7c,
        kSendRegistration = 0x7d,
        kMassSell = 0x7e,
        kMassBuy = 0x7f,
        kSell = 0x80,
        kLoginCharacter = 0x82,
        kGetMagicMail = 0x87,
        kReadMagicMail = 0x88,
        kDeleteMagicMail = 0x89,
        kSendMagicMail = 0x8a,
        kGetAuctionHallInfo = 0x8f,
        kFavoritesList = 0x91,
        kTakeItem = 0x96,
        kDropItem = 0x97,
        kPutIn = 0x98,
        kWearItem = 0x99,
        kTakeOffItem = 0x9a,
        kOpen = 0x9b,
        kClose = 0x9c,
        kStartCombat = 0xa0,
        kConsume = 0xa1,
        kSit = 0xa2,
        kStand = 0xa3,
        kGiveItem = 0xa4,
        kMemorize = 0xa5,
        kRob = 0xa6,
        kDyeItem = 0xa9,
        kTrade = 0xb1,
    };

}  // namespace protocol

#endif  // REALMSERVEREMULATOR_PROTOCOL_PACKET_TYPE_H_
